site_name: HyperUI Documentation
use_directory_urls: false
theme:
  name: 'material'
markdown_extensions:
    - codehilite:
    - pymdownx.superfences:
        preserve_tabs: true
nav:
- Getting Started: 'index.md'
- Main UI Concepts: 'uiConcepts.md'
- Advanced Usage: 'advanced.md'
- UI Elements:
    - 'Static Element': 'elemStatic.md'
    - 'Button': 'elemButton.md'
    - 'Checkbox': 'elemCheckbox.md'
    - 'Radio Button': 'elemRadioButton.md'
    - 'Slider': 'elemSlider.md'
    - 'Progress Bar': 'elemProgressBar.md'
    - 'Rotary Knob': 'elemKnob.md'
    - 'Dropdown': 'elemDropdown.md'
    - 'Single-line Input': 'elemInput.md'
    - 'Multi-line Input': 'elemMultilineInput.md'
    - 'Table': 'elemTable.md'
    - 'Horizontal Table': 'elemHorTable.md'
    - 'Grid': 'elemGrid.md'
    - 'Fixed Grid': 'elemFixedGrid.md'
    - 'Menu': 'elemMenu.md'
    - 'Splitter': 'elemSplitter.md'
    - 'Rich Text Element': 'elemRichText.md'
    - 'Color Element': 'elemColor.md'
- Properties and Element Types: 'builtInValues.md'
- Example Projects: 'exampleProjects.md'
