#pragma once

#define UI_COLLECTIONS_START_VALUE		200

DECLARE_COLLECTION_EXPLICIT(ResourceCurves, UI_COLLECTIONS_START_VALUE + 0);
DECLARE_COLLECTION_EXPLICIT_WITH_ROLE(ResourceUIElements, UI_COLLECTIONS_START_VALUE + 1, CollectionRoleUI);
DECLARE_COLLECTION_EXPLICIT(ResourceClips3D, UI_COLLECTIONS_START_VALUE + 2);
DECLARE_COLLECTION_EXPLICIT(ResourceFonts, UI_COLLECTIONS_START_VALUE + 3);
DECLARE_COLLECTION_EXPLICIT(ResourceRasterFonts, UI_COLLECTIONS_START_VALUE + 4);
DECLARE_COLLECTION_EXPLICIT_WITH_ROLE(ResourceAnimations, UI_COLLECTIONS_START_VALUE + 5, CollectionRoleGraphics);
DECLARE_COLLECTION_EXPLICIT_WITH_ROLE(ResourceColorPicker, UI_COLLECTIONS_START_VALUE + 6, CollectionRoleUI);